# -*- coding: utf-8 -*-
"""dip_projectt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1730xfr02r6YiJw-ifRg7A0OBmqudmvhZ
"""

from google.colab import drive
drive.mount('/content/drive')

import os

base_path = "/content/drive/MyDrive/Apple_Segmentation_Project"

print(os.listdir(base_path))

apple_path = "/content/drive/MyDrive/Apple_Segmentation_Project/apples_segmentation"

folders = os.listdir(apple_path)

print("Folders inside Apple Segmentation:")
print(folders)

for folder in folders:
    folder_path = os.path.join(apple_path, folder)

    if os.path.isdir(folder_path):
        files = os.listdir(folder_path)
        print(f"\n{folder}: {len(files)} files")
        print(files[:5])

apple_path = "/content/drive/MyDrive/Apple_Segmentation_Project/Apple Segmentation"

for folder in ["Sk_background", "wild", "max_data - Copy"]:
    folder_path = os.path.join(apple_path, folder)

    print("\n==============================")
    print("FOLDER:", folder)
    print("==============================")

    for root, dirs, files in os.walk(folder_path):
        print("Path:", root)
        print("Subfolders:", dirs)
        print("Files:", files[:10])
        print("Number of files:", len(files))

base_path = "/content/drive/MyDrive/Apple_Segmentation_Project"

print("Contents of project folder:")
for item in os.listdir(base_path):
    print(item)

for root, dirs, files in os.walk(base_path):
    print("\nPATH:", root)
    print("FOLDERS:", dirs)
    print("FILES:", files[:5])

import cv2
import matplotlib.pyplot as plt
test_path = "/content/drive/MyDrive/Apple_Segmentation_Project/apples_segmentation/max_data - Copy/test"


# Get original RGB images
image_files = [
    f for f in os.listdir(test_path)
    if "_obj_" in f.lower() and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

# Get mask images
mask_files = [
    f for f in os.listdir(test_path)
    if "_msk_" in f.lower() and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("RGB images:", len(image_files))
print("Mask images:", len(mask_files))

# Display first 3 RGB images and 3 masks
plt.figure(figsize=(15, 8))

for i in range(3):
    # Original image
    img_path = os.path.join(test_path, image_files[i])
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    plt.subplot(2, 3, i + 1)
    plt.imshow(img)
    plt.title("Original")
    plt.axis("off")

    # Find a mask with the same number
    image_number = image_files[i].split("_obj_")[1].split(".")[0]

    matching_masks = [
        f for f in mask_files
        if f"_msk_{image_number}." in f
    ]

    if matching_masks:
        mask_path = os.path.join(test_path, matching_masks[0])
        mask = cv2.imread(mask_path, 0)

        plt.subplot(2, 3, i + 4)
        plt.imshow(mask, cmap="gray")
        plt.title("Ground Truth Mask")
        plt.axis("off")

plt.tight_layout()
plt.show()

test_path = "/content/drive/MyDrive/Apple_Segmentation_Project/apples_segmentation/max_data - Copy/test"

# Select one apple image
image_file = "20_12_29_13_15_00_rgb_back_all_on_obj_1.jpg"

image_path = os.path.join(test_path, image_file)

# Read image
image = cv2.imread(image_path)

# Convert BGR to RGB for displaying
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Otsu thresholding
_, otsu_mask = cv2.threshold(
    gray,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# Display results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(gray, cmap="gray")
plt.title("Grayscale Image")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(otsu_mask, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.tight_layout()
plt.show()

import numpy as np

# Same image used in Otsu method
image_file = "20_12_29_13_15_00_rgb_back_all_on_obj_1.jpg"

image_path = os.path.join(test_path, image_file)

# Read image
image = cv2.imread(image_path)

# Convert BGR to RGB
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Convert RGB image to HSV
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

# Create masks for colored apple regions
# These ranges can detect red/orange apple regions
lower1 = np.array([0, 50, 40])
upper1 = np.array([20, 255, 255])

lower2 = np.array([160, 50, 40])
upper2 = np.array([180, 255, 255])

mask1 = cv2.inRange(hsv, lower1, upper1)
mask2 = cv2.inRange(hsv, lower2, upper2)

# Combine both masks
hsv_mask = cv2.bitwise_or(mask1, mask2)

# Display results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(hsv, cmap="hsv")
plt.title("HSV Image")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(hsv_mask, cmap="gray")
plt.title("HSV Segmentation")
plt.axis("off")

plt.tight_layout()
plt.show()

# Create a 5x5 kernel
kernel = np.ones((5, 5), np.uint8)

# Remove small noise
opening = cv2.morphologyEx(
    hsv_mask,
    cv2.MORPH_OPEN,
    kernel
)

# Fill small holes and gaps
closing = cv2.morphologyEx(
    opening,
    cv2.MORPH_CLOSE,
    kernel
)

# Create the final segmented apple
segmented = cv2.bitwise_and(
    image_rgb,
    image_rgb,
    mask=closing
)

# Display the results
plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.imshow(hsv_mask, cmap="gray")
plt.title("Original HSV Mask")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(closing, cmap="gray")
plt.title("After Morphological Processing")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(segmented)
plt.title("Final Segmented Apple")
plt.axis("off")

plt.tight_layout()
plt.show()

import os

# Show the mask filenames
mask_files = [
    f for f in os.listdir(test_path)
    if "_msk_" in f.lower()
]

print("Number of mask files:", len(mask_files))
print("First 20 mask files:")
for f in mask_files[:20]:
    print(f)

# Get original images and masks
image_files = [
    f for f in os.listdir(test_path)
    if "_obj_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

mask_files = [
    f for f in os.listdir(test_path)
    if "_msk_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

# Create a dictionary for masks
mask_dict = {}

for mask in mask_files:
    # Remove the mask number and extension
    key = mask.rsplit("_msk_", 1)[0]

    # Extract mask number
    number = mask.rsplit("_msk_", 1)[1].split(".")[0]

    mask_dict[(key, number)] = mask

# Find matching image-mask pairs
pairs = []

for image in image_files:

    key = image.rsplit("_obj_", 1)[0]
    number = image.rsplit("_obj_", 1)[1].split(".")[0]

    if (key, number) in mask_dict:
        pairs.append((image, mask_dict[(key, number)]))

print("Original images:", len(image_files))
print("Masks:", len(mask_files))
print("Matched image-mask pairs:", len(pairs))

print("\nFirst 10 matched pairs:")
for image, mask in pairs[:10]:
    print("Image:", image)
    print("Mask :", mask)
    print()

image_files = [
    f for f in os.listdir(test_path)
    if "_obj_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

mask_files = [
    f for f in os.listdir(test_path)
    if "_msk_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Number of original images:", len(image_files))
print("Number of mask images:", len(mask_files))

# Show filenames grouped by their main name
print("\nOriginal image examples:")
for f in image_files[:15]:
    print(f)

print("\nMask examples:")
for f in mask_files[:15]:
    print(f)

bv

# IoU (Jaccard Index)
def calculate_iou(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(true_mask, predicted_mask).sum()
    union = np.logical_or(true_mask, predicted_mask).sum()

    if union == 0:
        return 1.0

    return intersection / union


# Dice Score
def calculate_dice(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(true_mask, predicted_mask).sum()

    total = true_mask.sum() + predicted_mask.sum()

    if total == 0:
        return 1.0

    return (2 * intersection) / total


# Pixel Accuracy
def calculate_accuracy(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    correct_pixels = np.sum(true_mask == predicted_mask)
    total_pixels = true_mask.size

    return correct_pixels / total_pixels


print("Evaluation functions created successfully.")

# Take the first matched pair
image_file, mask_file = pairs[0]

# Read original image
image = cv2.imread(os.path.join(test_path, image_file))
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Read ground-truth mask
mask = cv2.imread(os.path.join(test_path, mask_file), cv2.IMREAD_GRAYSCALE)

# Display
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Apple Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(mask, cmap="gray")
plt.title("Ground Truth Mask")
plt.axis("off")

plt.tight_layout()
plt.show()

print("Original:", image_file)
print("Mask:", mask_file)

import pandas as pd
# Store results
results = []


# -----------------------------
# Evaluation functions
# -----------------------------

def calculate_iou(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(true_mask, predicted_mask).sum()
    union = np.logical_or(true_mask, predicted_mask).sum()

    if union == 0:
        return 1.0

    return intersection / union


def calculate_dice(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(true_mask, predicted_mask).sum()
    total = true_mask.sum() + predicted_mask.sum()

    if total == 0:
        return 1.0

    return (2 * intersection) / total


def calculate_accuracy(true_mask, predicted_mask):
    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    return np.mean(true_mask == predicted_mask)


# -----------------------------
# Process every image
# -----------------------------

for image_file, mask_file in pairs:

    # Read original image
    image = cv2.imread(os.path.join(test_path, image_file))

    # Read ground-truth mask
    true_mask = cv2.imread(
        os.path.join(test_path, mask_file),
        cv2.IMREAD_GRAYSCALE
    )

    # Make sure both have same size
    if image.shape[:2] != true_mask.shape[:2]:
        true_mask = cv2.resize(
            true_mask,
            (image.shape[1], image.shape[0]),
            interpolation=cv2.INTER_NEAREST
        )

    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # ==================================================
    # METHOD 1: OTSU THRESHOLDING
    # ==================================================

    _, otsu_mask = cv2.threshold(
        gray,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    # ==================================================
    # METHOD 2: HSV COLOR THRESHOLDING
    # ==================================================

    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    lower1 = np.array([0, 50, 40])
    upper1 = np.array([20, 255, 255])

    lower2 = np.array([160, 50, 40])
    upper2 = np.array([180, 255, 255])

    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)

    hsv_mask = cv2.bitwise_or(mask1, mask2)

    # Morphological processing
    kernel = np.ones((5, 5), np.uint8)

    hsv_mask = cv2.morphologyEx(
        hsv_mask,
        cv2.MORPH_OPEN,
        kernel
    )

    hsv_mask = cv2.morphologyEx(
        hsv_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    # ==================================================
    # Calculate metrics
    # ==================================================

    otsu_iou = calculate_iou(true_mask, otsu_mask)
    otsu_dice = calculate_dice(true_mask, otsu_mask)
    otsu_accuracy = calculate_accuracy(true_mask, otsu_mask)

    hsv_iou = calculate_iou(true_mask, hsv_mask)
    hsv_dice = calculate_dice(true_mask, hsv_mask)
    hsv_accuracy = calculate_accuracy(true_mask, hsv_mask)

    # Store results
    results.append({
        "Image": image_file,

        "Otsu IoU": otsu_iou,
        "Otsu Dice": otsu_dice,
        "Otsu Accuracy": otsu_accuracy,

        "HSV IoU": hsv_iou,
        "HSV Dice": hsv_dice,
        "HSV Accuracy": hsv_accuracy
    })


# Convert results to DataFrame
results_df = pd.DataFrame(results)

print("Evaluation completed!")
print("Number of images evaluated:", len(results_df))

results_df.head()

# Calculate average scores

average_results = results_df[
    [
        "Otsu IoU",
        "Otsu Dice",
        "Otsu Accuracy",
        "HSV IoU",
        "HSV Dice",
        "HSV Accuracy"
    ]
].mean()

print("AVERAGE SEGMENTATION RESULTS")
print("--------------------------------")

print("Otsu IoU      :", round(average_results["Otsu IoU"], 4))
print("Otsu Dice     :", round(average_results["Otsu Dice"], 4))
print("Otsu Accuracy :", round(average_results["Otsu Accuracy"], 4))

print()

print("HSV IoU       :", round(average_results["HSV IoU"], 4))
print("HSV Dice      :", round(average_results["HSV Dice"], 4))
print("HSV Accuracy  :", round(average_results["HSV Accuracy"], 4))

# Select the first matched image
image_file, mask_file = pairs[0]

# Read image
image = cv2.imread(os.path.join(test_path, image_file))
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Read ground-truth mask
true_mask = cv2.imread(
    os.path.join(test_path, mask_file),
    cv2.IMREAD_GRAYSCALE
)

# -----------------------------
# Method 1: Otsu
# -----------------------------
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

_, otsu_mask = cv2.threshold(
    gray,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

# -----------------------------
# Method 2: HSV
# -----------------------------
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

lower1 = np.array([0, 50, 40])
upper1 = np.array([20, 255, 255])

lower2 = np.array([160, 50, 40])
upper2 = np.array([180, 255, 255])

mask1 = cv2.inRange(hsv, lower1, upper1)
mask2 = cv2.inRange(hsv, lower2, upper2)

hsv_mask = cv2.bitwise_or(mask1, mask2)

# -----------------------------
# Morphological processing
# -----------------------------
kernel = np.ones((5, 5), np.uint8)

hsv_final = cv2.morphologyEx(
    hsv_mask,
    cv2.MORPH_OPEN,
    kernel
)

hsv_final = cv2.morphologyEx(
    hsv_final,
    cv2.MORPH_CLOSE,
    kernel
)

# -----------------------------
# Display comparison
# -----------------------------
plt.figure(figsize=(16, 4))

plt.subplot(1, 4, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 4, 2)
plt.imshow(true_mask, cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(1, 4, 3)
plt.imshow(otsu_mask, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.subplot(1, 4, 4)
plt.imshow(hsv_final, cmap="gray")
plt.title("HSV + Morphology")
plt.axis("off")

plt.tight_layout()
plt.show()

wild_path = "/content/drive/MyDrive/Apple_Segmentation_Project/test_wild/test_wild"

wild_images = [
    f for f in os.listdir(wild_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Number of wild test images:", len(wild_images))

print("\nFirst 10 wild images:")
for f in wild_images[:10]:
    print(f)

# Select only JPG images
wild_jpg = [
    f for f in wild_images
    if f.lower().endswith(".jpg")
]

print("Wild JPG images:", len(wild_jpg))

# Process first 6 wild images
for image_file in wild_jpg[:6]:

    # Read image
    image = cv2.imread(os.path.join(wild_path, image_file))
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Convert to HSV
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    # Red/orange apple color ranges
    lower1 = np.array([0, 50, 40])
    upper1 = np.array([20, 255, 255])

    lower2 = np.array([160, 50, 40])
    upper2 = np.array([180, 255, 255])

    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)

    hsv_mask = cv2.bitwise_or(mask1, mask2)

    # Morphological processing
    kernel = np.ones((5, 5), np.uint8)

    final_mask = cv2.morphologyEx(
        hsv_mask,
        cv2.MORPH_OPEN,
        kernel
    )

    final_mask = cv2.morphologyEx(
        final_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    # Segment the apple
    segmented = cv2.bitwise_and(
        image_rgb,
        image_rgb,
        mask=final_mask
    )

    # Display
    plt.figure(figsize=(12, 4))

    plt.subplot(1, 3, 1)
    plt.imshow(image_rgb)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 3, 2)
    plt.imshow(final_mask, cmap="gray")
    plt.title("HSV + Morphology Mask")
    plt.axis("off")

    plt.subplot(1, 3, 3)
    plt.imshow(segmented)
    plt.title("Segmented Apple")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

    print("Image:", image_file)

output_path = "/content/drive/MyDrive/Apple_Segmentation_Project/wild_results"

os.makedirs(output_path, exist_ok=True)

for image_file in wild_jpg:

    # Read image
    image = cv2.imread(os.path.join(wild_path, image_file))
    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # HSV conversion
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    lower1 = np.array([0, 50, 40])
    upper1 = np.array([20, 255, 255])

    lower2 = np.array([160, 50, 40])
    upper2 = np.array([180, 255, 255])

    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)

    hsv_mask = cv2.bitwise_or(mask1, mask2)

    # Morphological processing
    kernel = np.ones((5, 5), np.uint8)

    final_mask = cv2.morphologyEx(
        hsv_mask,
        cv2.MORPH_OPEN,
        kernel
    )

    final_mask = cv2.morphologyEx(
        final_mask,
        cv2.MORPH_CLOSE,
        kernel
    )

    # Segmented image
    segmented = cv2.bitwise_and(
        image_rgb,
        image_rgb,
        mask=final_mask
    )

    # Save segmented image
    output_file = os.path.join(
        output_path,
        "segmented_" + image_file
    )

    cv2.imwrite(
        output_file,
        cv2.cvtColor(segmented, cv2.COLOR_RGB2BGR)
    )

print("Wild test results saved successfully!")
print("Saved in:", output_path)

# Display all wild test results
for image_file in wild_jpg:

    original_path = os.path.join(wild_path, image_file)
    result_path = os.path.join(
        output_path,
        "segmented_" + image_file
    )

    original = cv2.imread(original_path)
    result = cv2.imread(result_path)

    original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)
    result = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(original)
    plt.title("Original: " + image_file)
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(result)
    plt.title("HSV + Morphology")
    plt.axis("off")

    plt.tight_layout()
    plt.show()

# Create comparison table

comparison = pd.DataFrame({
    "Metric": [
        "IoU (Jaccard)",
        "Dice Score",
        "Pixel Accuracy"
    ],
    "Otsu": [
        average_results["Otsu IoU"],
        average_results["Otsu Dice"],
        average_results["Otsu Accuracy"]
    ],
    "HSV + Morphology": [
        average_results["HSV IoU"],
        average_results["HSV Dice"],
        average_results["HSV Accuracy"]
    ]
})

# Convert values to percentages
comparison["Otsu"] = comparison["Otsu"] * 100
comparison["HSV + Morphology"] = comparison["HSV + Morphology"] * 100

# Round values
comparison = comparison.round(2)

print(comparison.to_string(index=False))

# Save comparison results to Google Drive

comparison_path = "/content/drive/MyDrive/Apple_Segmentation_Project/comparison_results.csv"

comparison.to_csv(comparison_path, index=False)

print("Comparison results saved successfully!")
print("Saved at:", comparison_path)

metrics = ["IoU", "Dice Score", "Pixel Accuracy"]

otsu_values = [23.71, 35.79, 30.60]
hsv_values = [44.54, 51.11, 60.10]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8, 5))

plt.bar(x - width/2, otsu_values, width, label="Otsu")
plt.bar(x + width/2, hsv_values, width, label="HSV + Morphology")

plt.xlabel("Evaluation Metrics")
plt.ylabel("Percentage (%)")
plt.title("Comparison of Otsu and HSV + Morphology")
plt.xticks(x, metrics)
plt.ylim(0, 100)
plt.legend()

plt.tight_layout()

graph_path = "/content/drive/MyDrive/Apple_Segmentation_Project/comparison_graph.png"
plt.savefig(graph_path, dpi=300)
plt.show()

print("Comparison graph saved successfully!")
print("Saved at:", graph_path)

output_path = "/content/drive/MyDrive/Apple_Segmentation_Project/wild_results"

result_files = [
    f for f in os.listdir(output_path)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

print("Number of wild results:", len(result_files))

plt.figure(figsize=(15, 12))

for i, file in enumerate(result_files):
    image = cv2.imread(os.path.join(output_path, file))
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    plt.subplot(4, 4, i + 1)
    plt.imshow(image)
    plt.title(file, fontsize=8)
    plt.axis("off")

plt.tight_layout()
plt.show()

wild_path = "/content/drive/MyDrive/Apple_Segmentation_Project/test_wild/test_wild"
result_path = "/content/drive/MyDrive/Apple_Segmentation_Project/wild_results"

# Select a few wild images for qualitative analysis
wild_files = [
    f for f in os.listdir(wild_path)
    if f.lower().endswith(".jpg")
]

# Display original and segmented result
for file in wild_files[:6]:

    original = cv2.imread(os.path.join(wild_path, file))
    original = cv2.cvtColor(original, cv2.COLOR_BGR2RGB)

    result_file = "segmented_" + file
    result = cv2.imread(os.path.join(result_path, result_file))
    result = cv2.cvtColor(result, cv2.COLOR_BGR2RGB)

    plt.figure(figsize=(10, 4))

    plt.subplot(1, 2, 1)
    plt.imshow(original)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(1, 2, 2)
    plt.imshow(result)
    plt.title("HSV + Morphology")
    plt.axis("off")

    plt.suptitle(file)
    plt.tight_layout()
    plt.show()

source_code = r'''
import os
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# APPLE FRUIT SEGMENTATION USING IMAGE PROCESSING
# ============================================================

# ------------------------------------------------------------
# 1. Dataset Paths
# ------------------------------------------------------------

test_path = "/content/drive/MyDrive/Apple_Segmentation_Project/apples_segmentation/max_data - Copy/test"

wild_path = "/content/drive/MyDrive/Apple_Segmentation_Project/test_wild/test_wild"

output_path = "/content/drive/MyDrive/Apple_Segmentation_Project/wild_results"


# ------------------------------------------------------------
# 2. Find Original Images and Ground-Truth Masks
# ------------------------------------------------------------

image_files = [
    f for f in os.listdir(test_path)
    if "_obj_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]

mask_files = [
    f for f in os.listdir(test_path)
    if "_msk_" in f.lower()
    and f.lower().endswith((".jpg", ".jpeg", ".png"))
]


# Match each original image with its corresponding mask

mask_dict = {}

for mask in mask_files:
    key = mask.rsplit("_msk_", 1)[0]
    number = mask.rsplit("_msk_", 1)[1].split(".")[0]
    mask_dict[(key, number)] = mask


pairs = []

for image in image_files:
    key = image.rsplit("_obj_", 1)[0]
    number = image.rsplit("_obj_", 1)[1].split(".")[0]

    if (key, number) in mask_dict:
        pairs.append((image, mask_dict[(key, number)]))


print("Original images:", len(image_files))
print("Masks:", len(mask_files))
print("Matched image-mask pairs:", len(pairs))


# ------------------------------------------------------------
# 3. Otsu Thresholding
# ------------------------------------------------------------

def otsu_segmentation(image):

    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply Otsu thresholding
    _, mask = cv2.threshold(
        gray,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    return mask


# ------------------------------------------------------------
# 4. HSV Color Segmentation
# ------------------------------------------------------------

def hsv_segmentation(image):

    # Convert BGR image to HSV
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    # HSV ranges for red/orange apple regions
    lower1 = np.array([0, 50, 40])
    upper1 = np.array([20, 255, 255])

    lower2 = np.array([160, 50, 40])
    upper2 = np.array([180, 255, 255])

    # Create masks
    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)

    # Combine both masks
    hsv_mask = cv2.bitwise_or(mask1, mask2)

    return hsv_mask


# ------------------------------------------------------------
# 5. Morphological Processing
# ------------------------------------------------------------

def morphological_processing(mask):

    # Create a 5x5 structuring element
    kernel = np.ones((5, 5), np.uint8)

    # Opening removes small noise
    opening = cv2.morphologyEx(
        mask,
        cv2.MORPH_OPEN,
        kernel
    )

    # Closing fills small holes
    closing = cv2.morphologyEx(
        opening,
        cv2.MORPH_CLOSE,
        kernel
    )

    return closing


# ------------------------------------------------------------
# 6. Evaluation Metrics
# ------------------------------------------------------------

def calculate_iou(true_mask, predicted_mask):

    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(
        true_mask,
        predicted_mask
    ).sum()

    union = np.logical_or(
        true_mask,
        predicted_mask
    ).sum()

    if union == 0:
        return 1.0

    return intersection / union


def calculate_dice(true_mask, predicted_mask):

    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    intersection = np.logical_and(
        true_mask,
        predicted_mask
    ).sum()

    total = true_mask.sum() + predicted_mask.sum()

    if total == 0:
        return 1.0

    return (2 * intersection) / total


def calculate_accuracy(true_mask, predicted_mask):

    true_mask = true_mask > 0
    predicted_mask = predicted_mask > 0

    return np.mean(true_mask == predicted_mask)


# ------------------------------------------------------------
# 7. Evaluate Otsu and HSV + Morphology
# ------------------------------------------------------------

otsu_iou = []
otsu_dice = []
otsu_accuracy = []

hsv_iou = []
hsv_dice = []
hsv_accuracy = []


for image_file, mask_file in pairs:

    # Read original image
    image = cv2.imread(
        os.path.join(test_path, image_file)
    )

    # Read ground-truth mask
    true_mask = cv2.imread(
        os.path.join(test_path, mask_file),
        cv2.IMREAD_GRAYSCALE
    )

    # Otsu segmentation
    otsu_mask = otsu_segmentation(image)

    # HSV segmentation
    hsv_mask = hsv_segmentation(image)

    # Morphological processing
    final_mask = morphological_processing(hsv_mask)

    # Otsu metrics
    otsu_iou.append(
        calculate_iou(true_mask, otsu_mask)
    )

    otsu_dice.append(
        calculate_dice(true_mask, otsu_mask)
    )

    otsu_accuracy.append(
        calculate_accuracy(true_mask, otsu_mask)
    )

    # HSV + Morphology metrics
    hsv_iou.append(
        calculate_iou(true_mask, final_mask)
    )

    hsv_dice.append(
        calculate_dice(true_mask, final_mask)
    )

    hsv_accuracy.append(
        calculate_accuracy(true_mask, final_mask)
    )


# Calculate average results

average_results = {
    "Otsu IoU": np.mean(otsu_iou),
    "Otsu Dice": np.mean(otsu_dice),
    "Otsu Accuracy": np.mean(otsu_accuracy),

    "HSV IoU": np.mean(hsv_iou),
    "HSV Dice": np.mean(hsv_dice),
    "HSV Accuracy": np.mean(hsv_accuracy)
}


print("\nAVERAGE SEGMENTATION RESULTS")
print("--------------------------------")
print("Otsu IoU      :", round(average_results["Otsu IoU"], 4))
print("Otsu Dice     :", round(average_results["Otsu Dice"], 4))
print("Otsu Accuracy :", round(average_results["Otsu Accuracy"], 4))

print("HSV IoU       :", round(average_results["HSV IoU"], 4))
print("HSV Dice      :", round(average_results["HSV Dice"], 4))
print("HSV Accuracy  :", round(average_results["HSV Accuracy"], 4))


# ------------------------------------------------------------
# 8. Create Comparison Table
# ------------------------------------------------------------

comparison = pd.DataFrame({
    "Metric": [
        "IoU (Jaccard)",
        "Dice Score",
        "Pixel Accuracy"
    ],

    "Otsu": [
        average_results["Otsu IoU"] * 100,
        average_results["Otsu Dice"] * 100,
        average_results["Otsu Accuracy"] * 100
    ],

    "HSV + Morphology": [
        average_results["HSV IoU"] * 100,
        average_results["HSV Dice"] * 100,
        average_results["HSV Accuracy"] * 100
    ]
})

comparison = comparison.round(2)

print("\nCOMPARISON")
print("--------------------------------")
print(comparison.to_string(index=False))


# Save comparison results

comparison_path = "/content/drive/MyDrive/Apple_Segmentation_Project/comparison_results.csv"

comparison.to_csv(
    comparison_path,
    index=False
)

print("\nComparison results saved at:")
print(comparison_path)


# ------------------------------------------------------------
# 9. Comparison Graph
# ------------------------------------------------------------

metrics = [
    "IoU",
    "Dice Score",
    "Pixel Accuracy"
]

otsu_values = [23.71, 35.79, 30.60]

hsv_values = [44.54, 51.11, 60.10]

x = np.arange(len(metrics))
width = 0.35

plt.figure(figsize=(8, 5))

plt.bar(
    x - width / 2,
    otsu_values,
    width,
    label="Otsu"
)

plt.bar(
    x + width / 2,
    hsv_values,
    width,
    label="HSV + Morphology"
)

plt.xlabel("Evaluation Metrics")
plt.ylabel("Percentage (%)")
plt.title("Comparison of Otsu and HSV + Morphology")

plt.xticks(
    x,
    metrics
)

plt.ylim(0, 100)

plt.legend()

plt.tight_layout()

graph_path = "/content/drive/MyDrive/Apple_Segmentation_Project/comparison_graph.png"

plt.savefig(
    graph_path,
    dpi=300
)

plt.show()

print("\nComparison graph saved at:")
print(graph_path)


# ------------------------------------------------------------
# 10. Test HSV Segmentation on Wild Images
# ------------------------------------------------------------

os.makedirs(
    output_path,
    exist_ok=True
)

wild_files = [
    f for f in os.listdir(wild_path)
    if f.lower().endswith(".jpg")
]


for image_file in wild_files:

    # Read wild image
    image = cv2.imread(
        os.path.join(wild_path, image_file)
    )

    # HSV segmentation
    hsv_mask = hsv_segmentation(image)

    # Morphological processing
    final_mask = morphological_processing(hsv_mask)

    # Extract segmented apple
    segmented = cv2.bitwise_and(
        image,
        image,
        mask=final_mask
    )

    # Save result
    output_file = os.path.join(
        output_path,
        "segmented_" + image_file
    )

    cv2.imwrite(
        output_file,
        segmented
    )


print("\nWild dataset segmentation completed.")

print("Results saved at:")
print(output_path)


# ------------------------------------------------------------
# END OF PROJECT
# ------------------------------------------------------------
'''

source_path = "/content/drive/MyDrive/Apple_Segmentation_Project/source_code.py"

with open(source_path, "w") as file:
    file.write(source_code)

print("source_code.py created successfully!")
print("Saved at:", source_path)

requirements = """numpy
pandas
opencv-python
matplotlib
"""

requirements_path = "/content/drive/MyDrive/Apple_Segmentation_Project/requirements.txt"

with open(requirements_path, "w") as file:
    file.write(requirements)

print("requirements.txt created successfully!")
print("Saved at:", requirements_path)

readme = """# Apple Fruit Segmentation Using Color-Based Thresholding and Morphological Image Processing

## 1. Project Overview

This mini project focuses on segmenting apple fruits from images using digital image processing techniques. Two segmentation approaches are compared: Otsu thresholding and HSV color-based segmentation with morphological processing.

The performance of both methods is evaluated using IoU (Jaccard), Dice Score, and Pixel Accuracy. The HSV + Morphology method is also tested on a separate wild apple dataset.

## 2. Problem Statement

Accurate segmentation of fruits from their background is an important image processing task in applications such as fruit quality inspection, automated agriculture, and computer vision. The objective of this project is to identify and extract apple regions from images while reducing unwanted background regions.

## 3. Objectives

- To preprocess apple images for segmentation.
- To segment apples using Otsu thresholding.
- To segment apples using HSV color thresholding.
- To improve segmentation using morphological operations.
- To compare the segmentation methods using quantitative metrics.
- To test the selected method on wild apple images.
- To identify limitations and possible failure cases.

## 4. Dataset

The project uses an apple segmentation dataset containing original apple images and corresponding ground-truth masks. A separate wild apple image dataset is used for qualitative testing.

The labeled images are used to calculate IoU, Dice Score, and Pixel Accuracy. The wild images do not have ground-truth masks and are therefore used for visual evaluation.

## 5. Methodology

The following image processing pipeline is used:

1. Read the apple image.
2. Convert the image into suitable color representations.
3. Apply Otsu thresholding as the first segmentation method.
4. Convert the image from BGR to HSV color space.
5. Apply HSV color thresholding to identify apple-colored regions.
6. Apply morphological opening to remove small noise.
7. Apply morphological closing to fill small holes.
8. Extract the segmented apple region.
9. Compare the predicted masks with ground-truth masks.
10. Test HSV + Morphology on wild apple images.

## 6. Techniques Used

### Otsu Thresholding

Otsu thresholding automatically determines a threshold value from the grayscale image and separates the image into foreground and background regions.

### HSV Color Thresholding

Hsv color space separates hue, saturation, and brightness information. Selected HSV ranges are used to identify red/orange apple regions.

### Morphological Operations

Morphological opening is used to remove small unwanted regions, while morphological closing helps fill small holes and connect nearby regions.

## 7. Evaluation Metrics

### IoU (Jaccard Index)

IoU measures the overlap between the predicted segmentation and the ground-truth mask.

### Dice Score

Dice Score measures the similarity between the predicted mask and the ground-truth mask.

### Pixel Accuracy

Pixel Accuracy measures the percentage of pixels classified correctly.

## 8. Results

The average results obtained from the labeled test images are:

| Metric | Otsu | HSV + Morphology |
|---|---:|---:|
| IoU (Jaccard) | 23.71% | 44.54% |
| Dice Score | 35.79% | 51.11% |
| Pixel Accuracy | 30.60% | 60.10% |

On the evaluated dataset, HSV + Morphology produced higher IoU, Dice Score, and Pixel Accuracy than Otsu thresholding.

## 9. Wild Dataset Testing

The HSV + Morphology method was applied to a separate wild apple dataset. The segmented results were saved in the `wild_results` folder.

Since ground-truth masks were not available for the wild images, these results were evaluated qualitatively by visually examining the segmentation output.

## 10. Limitations

- The HSV thresholds were selected for red/orange apple regions.
- Apples with significantly different colors may not be segmented correctly.
- Shadows and lighting variations can affect segmentation.
- Background objects with similar colors may be incorrectly included.
- Wild images do not have ground-truth masks, so quantitative evaluation was not possible for them.
- Simple threshold-based methods may be less robust in complex environments.

## 11. Future Scope

- Use adaptive or automatically optimized HSV thresholds.
- Include apples of different colors.
- Use advanced segmentation techniques such as GrabCut or watershed.
- Use machine learning or deep learning segmentation models.
- Increase the size and diversity of the dataset.
- Evaluate the system on more complex real-world images.

## 12. Conclusion

This project demonstrates apple fruit segmentation using classical digital image processing techniques. Otsu thresholding and HSV-based segmentation were implemented and compared. Based on the evaluated dataset, HSV + Morphology achieved higher segmentation scores than Otsu thresholding. The project also demonstrates the application of the selected method on wild apple images and identifies conditions that can affect segmentation performance.

## 13. Project Structure

```text
Apple_Segmentation_Project/
│
├── apples_segmentation/
├── test_wild/
├── wild_results/
├── comparison_results.csv
├── comparison_graph.png
├── source_code.py
├── requirements.txt
└── README.md
```"""

readme_path = "/content/drive/MyDrive/Apple_Segmentation_Project/README.md"

with open(readme_path, "w") as file:
    file.write(readme)

print("README.md created successfully!")
print("Saved at:", readme_path)

def otsu_segmentation(image):

    # Convert image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply Otsu thresholding
    _, mask = cv2.threshold(
        gray,
        0,
        255,
        cv2.THRESH_BINARY + cv2.THRESH_OTSU
    )

    return mask


def hsv_segmentation(image):

    # Convert BGR image to HSV
    hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)

    # HSV ranges for red/orange apple regions
    lower1 = np.array([0, 50, 40])
    upper1 = np.array([20, 255, 255])

    lower2 = np.array([160, 50, 40])
    upper2 = np.array([180, 255, 255])

    # Create masks
    mask1 = cv2.inRange(hsv, lower1, upper1)
    mask2 = cv2.inRange(hsv, lower2, upper2)

    # Combine both masks
    hsv_mask = cv2.bitwise_or(mask1, mask2)

    return hsv_mask


def morphological_processing(mask):

    # Create a 5x5 structuring element
    kernel = np.ones((5, 5), np.uint8)

    # Opening removes small noise
    opening = cv2.morphologyEx(
        mask,
        cv2.MORPH_OPEN,
        kernel
    )

    # Closing fills small holes
    closing = cv2.morphologyEx(
        opening,
        cv2.MORPH_CLOSE,
        kernel
    )

    return closing


# Paths
test_path = "/content/drive/MyDrive/Apple_Segmentation_Project/apples_segmentation/max_data - Copy/test"

results_path = "/content/drive/MyDrive/Apple_Segmentation_Project/result_images"
os.makedirs(results_path, exist_ok=True)

# Select the first matched image
image_file, mask_file = pairs[0]

# Read original image
image = cv2.imread(os.path.join(test_path, image_file))
image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

# Read ground-truth mask
true_mask = cv2.imread(
    os.path.join(test_path, mask_file),
    cv2.IMREAD_GRAYSCALE
)

# Apply Otsu
otsu_mask = otsu_segmentation(image)

# Apply HSV
hsv_mask = hsv_segmentation(image)

# Apply morphology
final_mask = morphological_processing(hsv_mask)

# Create comparison figure
plt.figure(figsize=(12, 8))

plt.subplot(2, 2, 1)
plt.imshow(image_rgb)
plt.title("Original Image")
plt.axis("off")

plt.subplot(2, 2, 2)
plt.imshow(true_mask, cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(2, 2, 3)
plt.imshow(otsu_mask, cmap="gray")
plt.title("Otsu Segmentation")
plt.axis("off")

plt.subplot(2, 2, 4)
plt.imshow(final_mask, cmap="gray")
plt.title("HSV + Morphology")
plt.axis("off")

plt.tight_layout()

# Save the result image
results_path = "/content/drive/MyDrive/Apple_Segmentation_Project/result_images"
os.makedirs(results_path, exist_ok=True)

save_path = os.path.join(
    results_path,
    "segmentation_comparison.png"
)

plt.savefig(
    save_path,
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Image saved successfully!")
print("Saved at:", save_path)

# Select the first wild image
wild_file = wild_jpg[0]

# Read image
wild_image = cv2.imread(
    os.path.join(wild_path, wild_file)
)

wild_image_rgb = cv2.cvtColor(
    wild_image,
    cv2.COLOR_BGR2RGB
)

# HSV segmentation
wild_hsv_mask = hsv_segmentation(wild_image)

# Morphological processing
wild_final_mask = morphological_processing(wild_hsv_mask)

# Extract segmented apple
wild_segmented = cv2.bitwise_and(
    wild_image_rgb,
    wild_image_rgb,
    mask=wild_final_mask
)

# Display
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.imshow(wild_image_rgb)
plt.title("Wild Original")
plt.axis("off")

plt.subplot(1, 3, 2)
plt.imshow(wild_final_mask, cmap="gray")
plt.title("HSV + Morphology Mask")
plt.axis("off")

plt.subplot(1, 3, 3)
plt.imshow(wild_segmented)
plt.title("Segmented Wild Apple")
plt.axis("off")

plt.tight_layout()

# Save
wild_result_image = os.path.join(
    results_path,
    "wild_apple_segmentation.png"
)

plt.savefig(
    wild_result_image,
    dpi=300,
    bbox_inches="tight"
)

plt.show()

print("Wild result image saved successfully!")
print("Saved at:", wild_result_image)